### ISSUE TITLE
Improve OpenTelemetry Operator Docs

### ISSUE THREAD

**Issue by Calm-Rock** [SigNoz/signoz-web#105]
https://signoz.io/docs/tutorial/opentelemetry-operator-usage/ - improve these docs.

**Comment by prashant-shahi** [comment]
> OTel Operator to SigNoz Cloud docs need to be added.

This is already resolved by https://github.com/SigNoz/signoz.io/pull/1620

If you wish to further improve the docs, you can go ahead with it.
If not, feel free to close this issue.

**Comment by Calm-Rock** [comment]
Closing this as a PR was raised for this - https://github.com/SigNoz/signoz.io/pull/1620
