### ISSUE TITLE
Create a sign-up form

### ISSUE THREAD

**Issue by ankit01-oss** [SigNoz/signoz-web#123]
Raise a PR with a page with the following [design](https://www.figma.com/file/VanpJ7C5uWJo4EVLlgLou3/SigNozForm?node-id=0-1) and having a URL: https://signoz.io/self-host/

The form should be implemented using [react hook form](https://react-hook-form.com/). Please apply basic validation checks on the form.

If you're applying through upwork, please send in a email to ankit.anand@signoz.io with your upwork proposal details.

Also, attaching a screenshot of the design:
<img width="969" alt="Screenshot 2023-03-29 at 1 56 47 PM" src="https://user-images.githubusercontent.com/83692067/228473345-95987982-cc43-4ff4-858c-2311d31684f4.png">

**Comment by Calm-Rock** [comment]
This is done. Closing the issue.
