### ISSUE TITLE
Enable ability to manually configure which blog items are shown in blog list page and in the left side panel 

### ISSUE THREAD

**Issue by pranay01** [SigNoz/signoz-web#165]
Currently the blog list page shows blogs based on recency. We should have flexibility to also configure this list based on what we want to highlight. 

The left side panel in any blog automatically shows recent articles. We should also have ability to manually configure it to show blogs related to the current blog

**Comment by zriyansh** [comment]
@pranay01 we do that now

**Comment by pranay01** [comment]
Closing, as this is no longer relevant in the new website design
