### ISSUE TITLE
[signoz.io] FE: Add a New label to new docs 

### ISSUE THREAD

**Issue by Calm-Rock** [SigNoz/signoz-web#198]
In the old website, we had a new label in the left navigation for the newly added docs. Checkout the LLM monitoring section on [this link](https://deploy-preview-1762--frosty-austin-928e43.netlify.app/docs/) for reference.

We need to have this tag in the new website as well. 

Some additional details:

- We add new sections (With multiple docs) as well as new doc (Sigle docs) to the website so this New Label should be such that it can be easily added to both of them.

You can checkout the old website repo to see how we added this in the old website - [GitHub link](https://github.com/SigNoz/signoz.io)

**Comment by ankit01-oss** [comment]
<img width="320" alt="Screenshot 2024-06-05 at 5 14 47 PM" src="https://github.com/SigNoz/signoz-web/assets/83692067/484f7130-43a4-422f-85ba-10343eaa7df8">

**Comment by Calm-Rock** [comment]
https://github.com/SigNoz/signoz-web/pull/255 - PR was raised and merged.

Closing
