### ISSUE TITLE
Docs for multiple ingestion keys

### ISSUE THREAD

**Issue by Calm-Rock** [SigNoz/signoz-web#263]
We should have docs for multiple ingestion Keys.

The docs could probably go under SigNoz Features section

**Comment by grandwizard28** [comment]
@Calm-Rock this feature has not gone to production yet. There's a lot of ongoing work related to the migration.

Will pick this task up post the feature is live for cloud users.

**Comment by Calm-Rock** [comment]
Okay @grandwizard28. Moving this under Engg-Pod and closing it here.
